
exchanges:
  - exchange: binance
    symbols: 
      - symbol: BTC/USDT
        watch_ticker: true
        watch_ohlcv: true
        watch_order_book: true
    interval: 1s
    is_synthetic: false
    api_credentials: {api_key: "", secret: ""}
  - exchange: coinbase
    symbols: 
      - symbol: BTC/USD
        watch_ticker: false
        watch_ohlcv: true
        watch_order_book: false
    interval: 1s
    is_synthetic: false
    api_credentials: {api_key: "", secret: ""}
  - exchange: kraken
    symbols: 
      - symbol: BTC/USD
        watch_ticker: true
        watch_ohlcv: false
        watch_order_book: true
    interval: 1s
    is_synthetic: false
    api_credentials: {api_key: "", secret: ""}
  - exchange: synthetic
    symbols:
      - symbol: BTCUSDT
        watch_ticker: true
        watch_ohlcv: true
        watch_order_book: true
    interval: 1s
    is_synthetic: true
